export const PLANNER_PERMISSIONS = [
  'planner.group.read',
  'planner.group.create',
  'planner.group.update',
  'planner.group.delete',
  'planner.group.member.read',
  'planner.group.member.write',
  'planner.plan.read',
  'planner.plan.create',
  'planner.plan.update',
  'planner.plan.delete',
  'planner.bucket.read',
  'planner.bucket.create',
  'planner.bucket.update',
  'planner.bucket.delete',
  'planner.task.read',
  'planner.task.create',
  'planner.task.update',
  'planner.task.assign',
  'planner.task.delete',
  'planner.task.comment.read',
  'planner.task.comment.create',
  'planner.task.comment.delete.any',
  'planner.group.member.role.set',
  'planner.group.link.m365',
  'planner.group.unlink',
  'planner.group.refresh',
  'planner.group.resolve-conflict',
  'planner.group.sync.mark-status',
  'planner.plan.link.m365',
  'planner.plan.unlink',
  'planner.plan.refresh',
  'planner.plan.resolve-conflict',
  'planner.plan.sync.mark-status',
  'planner.task.sync.mark-status',
] as const;
export type PlannerPermission = (typeof PLANNER_PERMISSIONS)[number];

export const PLANNER_ROLE_SLUGS = [
  'planner.admin',
  'planner.contributor',
  'planner.viewer',
  'system.integrations.m365',
] as const;
export type PlannerRoleSlug = (typeof PLANNER_ROLE_SLUGS)[number];

export const PLANNER_ROLE_PERMISSIONS: Record<PlannerRoleSlug, PlannerPermission[]> = {
  'planner.admin': [...PLANNER_PERMISSIONS],
  'system.integrations.m365': [
    'planner.group.read',
    'planner.group.member.read',
    'planner.group.update',
    'planner.group.member.write',
    'planner.group.member.role.set',
    'planner.group.sync.mark-status',
    'planner.plan.read',
    'planner.plan.update',
    'planner.plan.sync.mark-status',
    'planner.task.read',
    'planner.task.update',
    'planner.task.sync.mark-status',
  ],
  'planner.contributor': [
    'planner.group.read',
    'planner.group.member.read',
    'planner.plan.read',
    'planner.plan.create',
    'planner.plan.update',
    'planner.bucket.read',
    'planner.bucket.create',
    'planner.bucket.update',
    'planner.bucket.delete',
    'planner.task.read',
    'planner.task.create',
    'planner.task.update',
    'planner.task.assign',
    'planner.task.delete',
    'planner.task.comment.read',
    'planner.task.comment.create',
    'planner.group.refresh',
    'planner.plan.refresh',
  ],
  'planner.viewer': [
    'planner.group.read',
    'planner.group.member.read',
    'planner.plan.read',
    'planner.bucket.read',
    'planner.task.read',
    'planner.task.comment.read',
    'planner.task.comment.create',
    'planner.group.refresh',
    'planner.plan.refresh',
  ],
};
